version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: cadastroninjadb
    environment:
      POSTGRES_DB: CadastroDeNinjaDb
      POSTGRES_USER: cadastro_bd
      POSTGRES_PASSWORD: cadastro_bd
    ports:
      - "5431:5432"
    restart: always